bot:
  image: python2.7:bwts
  expose:
    - "5000"
  ports:
    - "5000:5000"
  environment:
    - SERVER_PORT=5000
    - HOST_ADDRESS=172.17.0.3
    - CONSUL_ADDRESS=172.16.30.254
    - CONSUL_PORT=8500
    - TAGS=master
    - VERSION=V1
