spring:
  profiles: expgateway

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_ADDRESS}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}

#need to sensitive cookies, in order to bring authorization headers to target
zuul:
  routes:
    gettoken:
      path: /security/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: authserver
    user:
      path: /userservice/**
      serviceId: userservice
      sensitiveHeaders: Cookie,Set-Cookie

security:
  oauth2:
    client:
      accessTokenUri: http://${AUTH_ADDR}/oauth/token
      userAuthorizationUri: http://${AUTH_ADDR}/oauth/authorize
      clientId: gateway
      clientSecret: gateway
    resource:
      userInfoUri: http://${AUTH_ADDR}/user
      token-info-uri: http://${AUTH_ADDR}/oauth/check_token
      grant-type: client_credentials
  sessions: ALWAYS
