spring:
  profiles: expgateway
  rabbitmq:
    host: ${RABBIT_ADDRESS}
    port: ${RABBIT_PORT}
    publisher-confirms: true
    virtual-host: /

server:
  port: ${SERVER_PORT}

#need to sensitive cookies, in order to bring authorization headers to target
zuul:
  routes:
    gettoken:
      path: /security/**
      sensitiveHeaders: Cookie,Set-Cookie
      serviceId: authservice
    user:
      path: /userservice/**
      serviceId: userservice
      sensitiveHeaders: Cookie,Set-Cookie

security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
    resource:
      userInfoUri: /user
      token-info-uri: /oauth/check_token



