spring:
  profiles: exp
  rabbitmq:
    host: ${RABBIT_ADDRESS}
    port: ${RABBIT_PORT}
    publisher-confirms: true
    virtual-host: /

server:
  port: ${SERVER_PORT}

#need to sensitive cookies, in order to bring authorization headers to target
zuul:
  routes:
    auth:
      path: /login/**
      serviceId: authservice
      sensitiveHeaders: Cookie,Set-Cookie
    user:
      path: /userservice/**
      serviceId: userservice
      sensitiveHeaders: Cookie,Set-Cookie
    lookup:
      path: /invoicelookup/**
      serviceId: invoicelookup
      sensitiveHeaders: Cookie,Set-Cookie
    inputs:
      path: /invoiceinputservice/**
      serviceId: invoiceinputservice
      sensitiveHeaders: Cookie,Set-Cookie

ribbon:
  ReadTimeout: 10000

security:
  oauth2:
    client:
      accessTokenUri: /oauth/token
      clientId: gateway
      clientSecret: gateway
    resource:
      userInfoUri: /user
      token-info-uri: /oauth/check_token


