---
spring:
  profiles: expauth
  rabbitmq:
    host: ${RABBIT_ADDRESS}
    port: ${RABBIT_PORT}
    publisher-confirms: true
    virtual-host: /
  datasource:
    url: jdbc:mysql://${AUTH_DB}/auth
    password: ${AUTH_DB_PWD}
    username: ${AUTH_DB_USER}

server:
  port: ${SERVER_PORT}
