# mvn spring-boot:run -Dspring.profiles.active=dev1
---
spring:
  profiles: profile1
  cloud:
    config:
      discovery:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${SERVER_ADDRESS}
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:18801/eureka/


server:
  port: ${SERVER_PORT}

content: has changed



