---
spring:
  profiles: profile1
  rabbitmq:
    addresses: amqp://ihsanever:guming0927@localhost:5672/
    host: localhost
    port: 5672
    username: ihsanever
    password: guming0927
    publisher-confirms: true
    virtual-host: /
  cloud:
    config:
      server:
        monitor:
          github:
            enable: true
      discovery:
        enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: localhost
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:18801/eureka/

server:
  port: 9091

endpoints:
  restart:
    enable: true

content: hi,you are successful from DemoA
---