---
spring:
  profiles: expeureka02

server:
  port: 18803

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://172.16.30.235:18802/eureka/
