---
spring:
  profiles: expeureka02

server:
  port: ${SERVER_PORT}

eureka:
  instance:
    prefer-ip-address: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}
