spring:
  profiles: explookup
  rabbitmq:
    host: ${RABBIT_ADDRESS}
    port: ${RABBIT_PORT}
    publisher-confirms: true
    virtual-host: /
  datasource:
    url: jdbc:mysql://${LOOKUP_DB}/lookup_portal?autoReconnect=true&useSSL=false

user:
  user-list:
    -
      id: ap
      host: http://${AP_ADDRESS}
    -
      id: invoice-image
      host: http://${INVOICE_IMAGE_ADDRESS}

robot:
  host: http://${BOT_SERVICE}/api/predictor