server:
    port: ${SERVER_PORT}

spring:
  profiles: expenv
  cloud:
      com.easeshift.config:
        discovery:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_ADDRESS}
