server:
    port: ${SERVER_PORT}

spring:
  profiles: profile1
  cloud:
      config:
        discovery:
          enabled: true

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_ADDRESS}