server:
  port: 18892

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:18801/eureka/

spring:
  cloud:
    com.easeshift.config:
      discovery:
        enabled: true

test:
  content: this is from github



