spring:
  profiles: profile1
  application:
    name: eureka-server-clustered

server:
  port: 18802

eureka:
  instance:
    hostname: eureka-profile1
    metadataMap:
      instanceId: ${spring.application.name}:${random.value}}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:18801/eureka/,http://localhost:18803/eureka/