spring:
  profiles: expuser
  datasource:
    url:  jdbc:mysql://${USER_DB}/tenant_user?autoReconnect=true&useSSL=false

server:
    port: ${SERVER_PORT}

hosts:
    frontend-host: http://${FRONT_ADDR}
