spring:
  profiles: expuser
  datasource:
    url:  jdbc:mysql://${USER_DB}/tenant_user?autoReconnect=true&useSSL=false

server:
    port: ${SERVER_PORT}

hosts:
    frontend-host: http://${FRONT_ADDR}

eureka:
  instance:
    prefer-ip-address: true
    ip-address: ${HOST_ADDRESS}
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: ${EUREKA_SERVERS}
