spring:
  profiles: exp
  rabbitmq:
    host: ${RABBIT_ADDRESS}
    port: ${RABBIT_PORT}
    publisher-confirms: true
    virtual-host: /
  datasource:
    url:  jdbc:mysql://${USER_DB}/tenant_user?autoReconnect=true&useSSL=false

server:
  port: ${SERVER_PORT}

ribbon:
  ReadTimeout: 10000

hosts:
  frontend-host: http://${FRONT_ADDR}

